#ifndef Define_h
#define Define_h

#define USE___SERIAL = 1;
#define USE_NEOPIXEL = 1;

const uint64_t MILLISECONDS_PER_SECOND = 1000;
const uint64_t MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60;
const uint64_t MICROSECONDS_PER_SECOND = MILLISECONDS_PER_SECOND * 1000;
const uint64_t MICROSECONDS_PER_MINUTE = MILLISECONDS_PER_MINUTE * 1000;

#endif